apiVersion: apps/v1
kind: Deployment 
metadata:
  name: k8s-deployment
spec:
  selector:
    matchLabels:
      app: k8s-deployment
  replicas: 2 
  template:
    metadata:
      labels:
        app: k8s-deployment
    spec:
      containers:
        - name: k8s-deployment
          image: my-ecr-repo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080


---

apiVersion: v1 
kind: Service 
metadata:
  name: k8s-service
spec:
  selector:
    app: k8s-service
  ports:
    - protocol: "TCP"
      port: 8080 
      targetPort: 8080 
  type: NodePort 
